apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-1
spec:
  storageClassName: nfs-storage
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/data/nfs-pv-1"
