apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server-deployment
  labels:
    app: config-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: config-server
  template:
    metadata:
      labels:
        app: config-server
    spec:
      containers:
        - name: config-server
          image: kozhenkov/config-server:latest
          ports:
            - name: http-port
              containerPort: 8888
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: http-port
            initialDelaySeconds: 10
            failureThreshold: 10
            timeoutSeconds: 2
            periodSeconds: 2
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: http-port
            initialDelaySeconds: 45
            timeoutSeconds: 2