kind: Service
apiVersion: v1
metadata:
  name: config-server-service
spec:
  selector:
    app: config-server
  type: ExternalName
  externalName: config-server
  ports:
    - port: 8888
      targetPort: 8888