kind: Service
apiVersion: v1
metadata:
  name: config-server-service
  namespace: dev
spec:
  selector:
    app: config-server
#  type: ExternalName
#  externalName: config-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8888