apiVersion: v1
kind: Service
metadata:
  name: {{ include "config-server.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ include "config-server.name" . }}
    helm.sh/chart: {{ include "config-server.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "config-server.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
