server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/link-aggregator
    username: postgres
    password: postgrespass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL82Dialect

message: 123